name: ci

on:
  push:
    branches:
      - '*'

jobs:
  dockerhub-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List directory structure
        run: ls -lah
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine tags
        id: tag
        run: |
          TIMESTAMP="$(date +'%Y%m%d%H%M%S')"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          NORMALIZED_BRANCH_NAME="${BRANCH_NAME//\//-}"
          if [[ $BRANCH_NAME == 'main' ]]; then
            echo "::set-output name=tag1::latest"
            echo "::set-output name=tag2::${TIMESTAMP}"
          else
            echo "::set-output name=tag1::latest-${NORMALIZED_BRANCH_NAME}"
            echo "::set-output name=tag2::${TIMESTAMP}-${NORMALIZED_BRANCH_NAME}"
          fi
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            vitobelgium/guppy:${{ steps.tag.outputs.tag1 }}
            vitobelgium/guppy:${{ steps.tag.outputs.tag2 }}
          context: ./server
          file: ./server/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max