name: ci

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/github-actions'

jobs:
  dockerhub-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List directory structure
        run: ls -lah
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Determine tag
        id: tag
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          NORMALIZED_BRANCH_NAME="${BRANCH_NAME/\//-}"
          if [[ $BRANCH_NAME == 'main' ]]; then
            echo "::set-output name=tag::latest"
          elif [[ $BRANCH_NAME == 'develop' ]]; then
            echo "::set-output name=tag::latest-dev"
          else
            echo "::set-output name=tag::${NORMALIZED_BRANCH_NAME}"
          fi
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            vitobelgium/guppy:${{ steps.tag.outputs.tag }}
            vitobelgium/guppy:${{ env.TIMESTAMP }}
          context: ./server
          file: ./server/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max